name: AirPulse Schedule Test

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"
      timezone: "Asia/Ho_Chi_Minh"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduled trigger
        run: |
          echo "SCHEDULE WORKS"
          date